

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Relogio from "@/components/relogio";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className="flex flex-col justify-start gap-4 p-10 items-center min-h-screen">
        {/* Header */}
        <header className="flex flex-col items-center w-full mb-6">
          <h1 className="text-3xl font-bold mb-2">React & Next.js</h1>
          <p>
            Hora atual: <Relogio />
          </p>
        </header>

        {/* Main */}
        <main className="bg-blue-200 p-5 rounded-2xl max-w-2xl w-full min-h-[70vh]">
          {children}
        </main>

        {/* Footer */}
        <footer className="w-full text-center mt-10 p-4 bg-gray-100 rounded-xl">
          DIW
        </footer>
      </body>
    </html>
  );
}
