import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Relogio from "@/components/relogio";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
    <html lang="en">
      <body className='flex flex-col justify-start gap-4 p-20 items-center min-h-screen'>
        
        <header className="flex flex-col items-center">
          <h1>React & Next.js</h1>
                  <footer
          style={{
            marginTop: "40px",
            padding: "20px",
            textAlign: "center",
            background: "#f0f0f0",
          }}
        >
          <p>Hora atual: <Relogio /></p>
        </footer>
        </header>
        
        <main className="bg-blue-200 p-5 rounded-2xl max-w-2xl min-h-[70vh]">
          {children}
        </main>
        
        <footer>DIW</footer>

      </body>
    </html>
  );
}
